import { Controller, Get, Param, UseGuards, Req, Res } from '@nestjs/common';
import { InvoicesService } from './invoices.service';
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard';
import { Response, Request } from 'express';

// eslint-disable-next-line @typescript-eslint/no-var-requires
const PDFDocument = require('pdfkit');

@Controller('invoices')
@UseGuards(JwtAuthGuard)
export class InvoicesController {
  constructor(private readonly invoicesService: InvoicesService) {}

  @Get('my-invoices')
  async getMyInvoices(@Req() req: Request) {
    const user = (req as any).user;
    return this.invoicesService.getCustomerInvoices(user.userId, user.email);
  }

  @Get(':id')
  async getInvoice(@Param('id') id: string, @Req() req: Request) {
    const user = (req as any).user;
    return this.invoicesService.getInvoiceById(id, user.userId, user.email);
  }

  @Get(':id/pdf')
  async getInvoicePdf(@Param('id') id: string, @Res() res: Response, @Req() req: Request) {
    const user = (req as any).user;
    const invoice = await this.invoicesService.getInvoiceById(id, user.userId, user.email);
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=invoice-${invoice.invoiceNumber}.pdf`);

    const doc = new PDFDocument({ margin: 50 });
    doc.pipe(res);

    doc.fontSize(24).text('INVOICE', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).text(`Invoice #: ${invoice.invoiceNumber}`, { align: 'right' });
    doc.text(`Date: ${new Date(invoice.createdAt).toLocaleDateString()}`, { align: 'right' });
    doc.text(`Status: ${invoice.status.toUpperCase()}`, { align: 'right' });
    
    doc.moveDown(2);
    doc.fontSize(12).text('SAABIZ - Merchant of Record Platform', { align: 'center' });
    
    doc.moveDown(2);
    doc.fontSize(14).text('Bill To:');
    doc.fontSize(10).text(invoice.buyer.email);
    
    doc.moveDown();
    doc.fontSize(14).text('From:');
    doc.fontSize(10).text(invoice.seller.name);
    doc.text(invoice.seller.email);

    doc.moveDown(2);
    doc.fontSize(14).text('Items:', { underline: true });
    doc.moveDown();
    
    const tableTop = doc.y;
    doc.fontSize(10);
    doc.text('Description', 50, tableTop);
    doc.text('Plan', 250, tableTop, { width: 100 });
    doc.text('Amount', 400, tableTop, { width: 100, align: 'right' });
    
    doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();
    
    doc.text(invoice.product.name, 50, tableTop + 20);
    doc.text(invoice.plan.name, 250, tableTop + 20, { width: 100 });
    doc.text(`₦${invoice.total.toFixed(2)}`, 400, tableTop + 20, { width: 100, align: 'right' });

    if (invoice.product.description) {
      doc.fontSize(8).text(invoice.product.description, 50, tableTop + 35, { width: 500 });
    }

    doc.moveDown(4);
    doc.fontSize(12);
    doc.text(`Total: ₦${invoice.total.toFixed(2)}`, { align: 'right' });

    doc.moveDown(2);
    doc.fontSize(10).text('Payment Details:', { underline: true });
    doc.fontSize(9);
    doc.text(`Gateway: ${invoice.payment.gateway}`);
    doc.text(`Reference: ${invoice.payment.reference}`);
    doc.text(`Date: ${new Date(invoice.payment.date).toLocaleDateString()}`);

    doc.moveDown(3);
    doc.fontSize(8).text('Thank you for your business!', { align: 'center' });
    doc.text('This invoice was generated by SAABIZ - Merchant of Record Platform', { align: 'center' });

    doc.end();
  }

  @Get(':id/html')
  async getInvoiceHtml(@Param('id') id: string, @Res() res: Response, @Req() req: Request) {
    const user = (req as any).user;
    const invoice = await this.invoicesService.getInvoiceById(id, user.userId, user.email);
    
    const html = this.generateInvoiceHtml(invoice);
    
    res.setHeader('Content-Type', 'text/html');
    res.setHeader('Content-Disposition', `attachment; filename=invoice-${invoice.invoiceNumber}.html`);
    res.send(html);
  }

  private generateInvoiceHtml(invoice: any): string {
    return `<!DOCTYPE html>
<html>
<head>
  <title>Invoice ${invoice.invoiceNumber}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
    .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
    .invoice-title { font-size: 32px; color: #333; }
    .invoice-details { text-align: right; }
    .section { margin: 20px 0; }
    .section-title { font-size: 18px; font-weight: bold; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 15px; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background-color: #f5f5f5; }
    .total { font-size: 20px; font-weight: bold; text-align: right; margin-top: 20px; }
    .footer { margin-top: 50px; text-align: center; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <h1 class="invoice-title">INVOICE</h1>
      <p><strong>SAABIZ</strong><br>Merchant of Record Platform</p>
    </div>
    <div class="invoice-details">
      <p><strong>Invoice #:</strong> ${invoice.invoiceNumber}</p>
      <p><strong>Date:</strong> ${new Date(invoice.createdAt).toLocaleDateString()}</p>
      <p><strong>Status:</strong> ${invoice.status.toUpperCase()}</p>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Bill To</div>
    <p>${invoice.buyer.email}</p>
  </div>

  <div class="section">
    <div class="section-title">From</div>
    <p><strong>${invoice.seller.name}</strong><br>${invoice.seller.email}</p>
  </div>

  <div class="section">
    <div class="section-title">Items</div>
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th>Plan</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>${invoice.product.name}<br><small>${invoice.product.description || ''}</small></td>
          <td>${invoice.plan.name}</td>
          <td>₦${invoice.total.toFixed(2)}</td>
        </tr>
      </tbody>
    </table>
    <div class="total">
      <p>Total: ₦${invoice.total.toFixed(2)}</p>
    </div>
  </div>

  <div class="section">
    <div class="section-title">Payment Details</div>
    <p><strong>Gateway:</strong> ${invoice.payment.gateway}</p>
    <p><strong>Reference:</strong> ${invoice.payment.reference}</p>
    <p><strong>Date:</strong> ${new Date(invoice.payment.date).toLocaleDateString()}</p>
  </div>

  <div class="footer">
    <p>Thank you for your business!</p>
    <p>This invoice was generated by SAABIZ - Merchant of Record Platform</p>
  </div>
</body>
</html>`;
  }
}
